# -*- coding: utf-8 -*-
"""sentiment_analysis+Topic_model.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1RSlmf3tl341ug4bCrCL12LDfsCX6RmLN
"""

import pandas as pd

sheet_id = "1NOmVVECrN8BJQ-ZAAjpWt0Hbmd2hNCg5"
url = f"https://docs.google.com/spreadsheets/d/{sheet_id}/export?format=csv"

df = pd.read_csv(url)
df.head()

df.columns

df.drop(columns = ["Unnamed: 0" , "id"])

df = df.rename(columns ={"clean_content":"content"})

"""# sentiment analysis (multiling)"""

df.columns

!pip install -q transformers tqdm torch

from transformers import AutoTokenizer, AutoModelForSequenceClassification, pipeline
from tqdm import tqdm
import pandas as pd
import torch

# Make sure GPU is available
device = 0 if torch.cuda.is_available() else -1
print(f"Using device: {'GPU' if device == 0 else 'CPU'}")

# Load model (fast tokenizer works fine here)
model_name = "cardiffnlp/twitter-xlm-roberta-base-sentiment"

tokenizer = AutoTokenizer.from_pretrained(model_name, use_fast=True)
model = AutoModelForSequenceClassification.from_pretrained(model_name)

sentiment_model = pipeline(
    "sentiment-analysis",
    model=model,
    tokenizer=tokenizer,
    device=device,
    truncation=True,
    max_length=512,
    batch_size=16,
)



# Convert to list
texts = df['content'].astype(str).tolist()

# Run inference
results = []
for i in tqdm(range(0, len(texts), 32)):
    batch = texts[i:i+32]
    results.extend(sentiment_model(batch))

# Store results
df["sent_label"] = [r["label"] for r in results]
df["sent_score"] = [r["score"] for r in results]

df.head()

label_map = {
    "LABEL_0": "negative",
    "LABEL_1": "neutral",
    "LABEL_2": "positive"
}
df["sent_label"] = df["sent_label"].map(label_map)

df["sent_label"].value_counts(normalize=True)

"""# topic modeling (multiling)"""

from bertopic import BERTopic
from sentence_transformers import SentenceTransformer

# multilingual MiniLM = light and good
embedding_model = SentenceTransformer("paraphrase-multilingual-MiniLM-L12-v2")

docs = df["content"].astype(str).tolist()

topic_model = BERTopic(
    embedding_model=embedding_model,
    language="multilingual",
    verbose=True,
    min_topic_size=20
)

topics, probs = topic_model.fit_transform(docs)

df["topic_id"] = topics

# get top words for each topic
topic_info = topic_model.get_topic_info()
topic_info.head()

def get_topic_label(tid):
    if tid == -1:
        return "other"
    top_words = [word for word, _ in topic_model.get_topic(tid)[:3]]
    return ", ".join(top_words)

df["topic_name"] = df["topic_id"].apply(get_topic_label)

df["topic_name"].value_counts().head(10)

df[df["sent_label"]=="negative"]["topic_name"].value_counts().head(10)

# save df

df.to_csv("feedback_with_sentiment_topics.csv", index=False)
print(" Saved with sentiment and topic columns.")

